---
name: yaml-lint
on: [push, pull_request]

jobs:
  build:
    name: YAML Lint
    runs-on: ubuntu-22.04

    steps:
      - name: Check out the codebase
        uses: actions/checkout@v3.3.0
        with:
          path: 'sebdanielsson.cloudflared'
          fetch-depth: 0


      - name: YAML Lint
        uses: ibiqlik/action-yamllint@v3.1.1
        with:
          config_file: sebdanielsson.cloudflared/.yamllint
